import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Kitap sidebar'ı kitap/ klasör yapısından otomatik üretilir.
// Sıralama: kitap/index.md (sidebar_position: 0) → Kısım I–V → Ekler → Kaynaklar (position: 99)
const sidebars: SidebarsConfig = {
  kitapSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
