import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Kütüphane sidebar'ı kutuphane/ klasör yapısından otomatik üretilir.
const sidebars: SidebarsConfig = {
  kutuphaneSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
