import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// Araçlar sidebar'ı araclar/ klasör yapısından otomatik üretilir.
const sidebars: SidebarsConfig = {
  araclarSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
